# Generated by Django 4.0.5 on 2022-07-12 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hangouts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='due_date',
            field=models.DateField(),
        ),
    ]
