# Generated by Django 4.0.5 on 2022-07-14 00:19

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hangouts', '0002_alter_event_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, default='', max_length=255, null=True, verbose_name='media/'),
        ),
    ]
