# Generated by Django 4.0.5 on 2022-07-14 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hangouts', '0003_alter_event_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='photo',
            field=models.ImageField(blank=True, default='', null=True, upload_to='media/'),
        ),
    ]
